language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# Command to install dependency.
install: "pip install -r requirements.txt"

# Command to run tests.
script: python tests.py
